title: Ser-Drephs # name of the site
author: Sergei Drevs (Ser-Drephs) # name of site's author
url: https://ser-drephs.github.io # root address of the site
description: > # description of the site (multiple lines allowed)
  My personal landing page.

permalink: /:title.html

baseurl : ''
disqus: ''
mailchimp-list : ''

favicon: "./logo.png" # relative path to site's favicon

theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
